# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Alpha
  jobs:
  - job: Core
    displayName: 'Build and Publish Stoic Dreams Core'
    pool:
      vmImage: 'windows-latest'
    variables:
      buildConfiguration: 'Release'
    steps:
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '6.x'
          checkLatest: true
      - task: UseDotNet@2
        displayName: 'Load the SDK'
        inputs:
          packageType: 'sdk'
          version: '7.x'
          includePreviewVersions: false
      - task: DotNetCoreCLI@2
        displayName: 'Restore nuget packages'
        inputs:
          command: 'restore'
          projects: '**/*.sln'
          includeNuGetOrg: true
      - task: DotNetCoreCLI@2
        displayName: 'Build and pack the project'
        inputs:
          command: 'build'
          projects: '**/*.sln'
      - task: VisualStudioTestPlatformInstaller@1
      - task: DotNetCoreCLI@2
        displayName: 'Run Build Tests'
        inputs:
          command: 'test'
          projects: '**/*.BuildTests.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore --collect: "XPlat Code Coverage"'
          publishTestResults: true,
          nobuild: true
      - script: "dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8"
        displayName: "Install ReportGenerator tool"
      - script: 'reportgenerator -reports:**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'
        displayName: "Create reports"
      - task: PublishCodeCoverageResults@1
        displayName: "Publish code coverage report"
        inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml"
      - task: Bash@3
        displayName: 'Push package to nuget store'
        inputs:
          targetType: inline
          script: dotnet nuget push --api-key $(NugetApiKey) --skip-duplicate --source $(NugetSource) '$(Agent.BuildDirectory)\NugetPackages\StoicDreams.Core.*.nupkg' > nugetpush.txt; echo $(cat nugetpush.txt)
      - task: Bash@3
        displayName: 'Echo version number.'
        inputs:
          targetType: inline
          script: pushResult=$(cat nugetpush.txt); re=".*StoicDreams\.Core\.([0-9\.]+)\.nupkg.*";if [[ $pushResult =~ $re ]]; then echo ${BASH_REMATCH[1]}; fi
